name: package

on: push

jobs:
  clone-and-build-and-package-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set env
        run: |
          echo "UBUNTU_VERSION=24.04" >> $GITHUB_ENV &&
          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV &&
          echo "TZ=Etc/UTC" >> $GITHUB_ENV

      - name: Update system package info
        run: apt-get -y update

      - name: Install toolchain
        run: apt-get -y install python3 gcc g++ libssl-dev curl sudo git

      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: ./install-system-packages.sh

      # - name: Test cargo
      #   run: cargo --help

      # - name: Fix dubious ownership
      #   run: git config --global --add safe.directory /__w/watchman/watchman

      - name: Build Watchman binaries
        run: ./autogen.sh

      # - name: Make .deb
      #   run: ./watchman/build/package/make-deb.sh
